apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sees-earth
  namespace: gigantic-computer
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: sees-earth
    spec:
      containers:
      - name: sees-earth
        image: 541790730179.dkr.ecr.us-east-1.amazonaws.com/sees-earth
        ports:
          - name: http
            containerPort: 80
